### PR TITLE
despace_ssse3_lut_1kb: faster comparison

### PR DESCRIPTION
**Pull request by kloetzl**
The original comparison can be improved by shaving off a few instructions and cycles. The unit tests run through. A similar method could also be used for most other functions, given my method is correct and I didn't miss an edge case.

ps. Thanks for this repo. The code is really helpful!

### CODE REVIEW

**Comment by lemire** [comment]
Thanks. What happens if a character with byte value 64 is included... do you expect your approach to work?

**Comment by kloetzl** [comment]
Unless I am missing something, that will work just fine. Consider the string `"@b c"` aka. `0x40622063`. After the shuffle that becomes `0x20002000`. Comparing that to the original string gives `0x0000FF00`.

It is basically a simplification over what you use in [simdjson](https://github.com/lemire/simdjson/blob/eba02dc1b997a36d06f97af542f45291d05fcdba/singleheader/simdjson.cpp#L220-L223) that works as long as all characters of interest have differing low nibbles.

**Comment by aqrit** [comment]
That's a neat trick!

btw, here is the despacer I was fiddling with last week
https://gist.github.com/aqrit/6e73ca6ff52f72a2b121d584745f89f3#file-despace-cpp-L141

**Comment by lemire** [comment]
I'm sold, merging.

**Comment by kloetzl** [comment]
> That's a neat trick!

Thanks! And thanks for merging! I haven't yet tried to extend the method to any of the other functions. Might be worth it.

**Pull request merged**
